type Encounters = Record<string, string[]>;

const encounters: Encounters = {
  fanatic: ["Cultist"],
  typos: ["Typo", "Typo"],
  test: ["Rat", "Goblin"],
  coup: ["Pointar"],
  eviction: ["Homeowner", "Homeowner", "Homeowner"],
  leaks: ["Leak", "Leak"],
  mob_stacking: ["Minion", "Minion", "Minion", "Minion", "Duelist"],
  avalanche: ["Pebble", "Rocko"],
  hooliga_n_s: ["Hooligan", "Hooligan", "Hooligan"],
  rescue: ["Oh_rangutang", "Oh_rangutang", "Oh_rangutang"],
  exterminator: ["Rat", "Rat", "Spider"],
  blockage: ["Beaver", "Beaver"],
  malfunction: ["Rogue_Soldier"],
  prophet: ["Tuo", "Tuos_Complement"],
  irrational: ["Root2", "Pi"],
  blight: ["Blighted_Tree", "Blighted_Tree"],
  greed: ["Thief", "Thief", "Thief"],
  postal: ["Bubbles"],
  protest: ["Angry_Student", "Angry_Student", "Angry_Student"],
  overdue: ["Overdue_Queuesgardian", "Overdue_Queuesgardian"],
  mad_scientist: ["Euler"],
  blight_fae: ["Blight_Fae"],
  family_feud_i: ["Tavern"],
  family_feud_ii: ["Mick"],
  family_feud_iii: ["Tector", "Jimbo"],
  demolition_man: ["Demolitionist"],
  severed: ["Edge", "Edge", "Edge"],
  last_wish: ["WishEnder"],
  the_end: ["TechnicaIngoramus"],
};

export default encounters;
